### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by tinykidpro** [abhaybd/Influence#14]
I really need instructions on how to install source code to run on CentOS or Ubuntu

**Comment by abhaybd** [comment]
This personal project is unmaintained and largely undocumented, so I won't give an in-depth explanation. The frontend can be installed and run as a standard react project (using `npm install` and `npm start`), the backend is a Java servlet so you can generate a WAR file with maven and then deploy it with a servlet container like Tomcat.

You should be able to google your way through that, good luck!
