### ISSUE TITLE
Firefox Issue

### ISSUE THREAD

**Issue by iwangy** [abhaybd/Influence#2]
When testing on Firefox Browser unable to start game in separate tab and throws an error

**Comment by iwangy** [comment]
![image](https://user-images.githubusercontent.com/35878784/89742509-79441d00-da4f-11ea-939b-4c8eb68ed8c2.png)
![image](https://user-images.githubusercontent.com/35878784/89742514-83661b80-da4f-11ea-8118-d425dac02846.png)

**Comment by abhaybd** [comment]
Fixed in cc32673
